{
 "title": "WebLogic Server Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "expr": "wls_jvm_heap_free_percent" }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "wls_jvm_heap_size_current", "legendFormat": "heap size" },
    { "expr": "wls_jvm_heap_free_current", "legendFormat": "heap free" }
   ]
  },
  {
   "title": "Datasources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_datasource_active_connections_current_count",
     "legendFormat": "({{name}}) connections"
    },
    { "expr": "wls_datasource_curr_capacity", "legendFormat": "({{name}}) capacity" }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_threadpool_execute_thread_total_count",
     "legendFormat": "threads"
    },
    { "expr": "wls_threadpool_queue_length", "legendFormat": "queue" },
    {
     "expr": "wls_threadpool_hogging_thread_count",
     "legendFormat": "hogging"
    },
    {
     "expr": "wls_threadpool_stuck_thread_count",
     "legendFormat": "stuck"
    }
   ]
  },
  {
   "title": "JMS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    { "expr": "wls_jms_messages_high_count", "legendFormat": "({{jmsserver}}) high" },
    { "expr": "wls_jms_messages_current_count", "legendFormat": "({{jmsserver}}) current" }
   ]
  },
  {
   "title": "Web App Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "wls_servlet_execution_time_average{app=~\"simpleear|wls-exporter\"}",
     "legendFormat": "({{app}}, {{servletName}}) avg execution"
    },
    {
     "expr": "wls_servlet_execution_time_high{app=~\"simpleear|wls-exporter\"}",
     "legendFormat": "({{app}}, {{servletName}}) high execution"
    }
   ]
  }
 ]
}