{
 "title": "Datasources Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wls_datasource_curr_capacity", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Waiting for Connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_datasource_waiting_for_connection_current_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_datasource_active_connections_current_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Leaked Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_datasource_leaked_connection_count",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}