{
 "title": "JMS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Message Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_jms_destination_messages_current_count",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Messages High Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_jms_destination_messages_high_count",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_jms_destination_consumers_current_count",
     "legendFormat": "{{destination}}"
    }
   ]
  }
 ]
}